# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.2'
  pod 'SDWebImage', '~> 5.8.4'
  pod 'RealmSwift', '~> 5.3.5'
  pod 'JGProgressHUD', '~> 2.1'

#  pod 'Firebase/Core'
#  pod 'Firebase/Database'
#  pod 'Firebase/Auth'
#  pod 'Firebase/Firestore'

end
